In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,5,"ram", 4+8j])

array(['1', '2', '3', '4', '5', 'ram', '(4+8j)'], dtype='<U64')

In [7]:
np.array([1,23,1,2,5.0])

array([ 1., 23.,  1.,  2.,  5.])

it upcasts all the data into biggest nature of data type

In [9]:
np.array([[1,3],[2,5],[6,7]])

array([[1, 3],
       [2, 5],
       [6, 7]])

In [10]:
np.array([[1,3],[2,5],[6,7,8]])

C:\Users\SAIRAM~1\AppData\Local\Temp/ipykernel_37912/1446999149.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[2,5],[6,7,8]])


array([list([1, 3]), list([2, 5]), list([6, 7, 8])], dtype=object)

In [14]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [18]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [19]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
arr = np.array([(1,2),(3,4)],dtype = [("a",'<i4'),("b",'<i8')])

In [40]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [41]:
type(arr[0][0])

numpy.int32

In [42]:
type(arr[0][1])

numpy.int64

In [43]:
arr[1][1]

4

In [44]:
type(arr[1][1])

numpy.int64

In [45]:
arr = np.array([[1,3],[3,4]])

In [46]:
arr

array([[1, 3],
       [3, 4]])

## array vs matrix

In [54]:
mat = np.mat(arr)
mat

matrix([[1, 3],
        [3, 4]])

In [48]:
l = [3,4,5,6,7]

In [49]:
np.array(l)

array([3, 4, 5, 6, 7])

In [50]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [56]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [57]:
np.asanyarray(mat) #which wont convert any kind of array

matrix([[1, 3],
        [3, 4]])

In [59]:
np.asarray(mat) #which converts the data type to array

array([[1, 3],
       [3, 4]])

In [60]:
issubclass(np.matrix, np.ndarray)

True

In [61]:
issubclass(np.ndarray, np.matrix)

False

In [65]:
a = arr
a

array([[1, 3],
       [3, 4]])

In [66]:
b = np.copy(arr)  #
b

array([[1, 3],
       [3, 4]])

In [72]:
arr[0][0] = 67 #array elements are mutable

In [73]:
arr #shallow copy - 

array([[67,  3],
       [ 3,  4]])

In [74]:
a

array([[67,  3],
       [ 3,  4]])

In [75]:
b

array([[1, 3],
       [3, 4]])

In [76]:
b[0][0] = 68  #deep copy --

In [77]:
b

array([[68,  3],
       [ 3,  4]])

In [78]:
arr[0:]

array([[67,  3],
       [ 3,  4]])

In [79]:
arr[-1]

array([3, 4])

In [80]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [83]:
np.fromfunction(lambda i, j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [85]:
type(np.fromfunction(lambda i, j :i==j,(4,4)))

numpy.ndarray

In [86]:
np.fromfunction(lambda i, j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [87]:
np.fromfunction(lambda i, j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [88]:
np.fromfunction(lambda i, j :i/j,(3,3))

C:\Users\SAIRAM~1\AppData\Local\Temp/ipykernel_37912/2665923418.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j :i/j,(3,3))
C:\Users\SAIRAM~1\AppData\Local\Temp/ipykernel_37912/2665923418.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [92]:
[i*i for i in range(5)] #list comprehension

[0, 1, 4, 9, 16]

In [91]:
def test(x):
    yield x

In [93]:
test(5)

<generator object test at 0x000001EADB77A200>

In [94]:
gen = (i*i for i in range(5))

In [95]:
gen

<generator object <genexpr> at 0x000001EADB77A510>

In [97]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [98]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [102]:
gen
for i in gen:
    print(i)

In [105]:
np.fromstring("1,2,3,6,5",sep = ',', dtype = int)

array([1, 2, 3, 6, 5])

In [109]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [4,5,6,7]])

In [110]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [111]:
type(arr1)

numpy.ndarray

In [112]:
arr1.ndim

2

In [113]:
arr1.size

12

In [114]:
arr1.shape

(3, 4)

In [115]:
arr1.dtype

dtype('int32')

In [116]:
arr.size

4

In [117]:
arr.ndim

2

In [118]:
arr.shape

(2, 2)

In [124]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [125]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [128]:
arr2.size

16

In [129]:
arr2.ndim

3

In [130]:
arr2.shape

(2, 2, 4)

In [133]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [134]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [135]:
arr4.ndim

4

In [136]:
arr4.shape

(1, 4, 2, 4)

In [139]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [145]:
list(np.arange(6.6,9,0.3))

[6.6,
 6.8999999999999995,
 7.199999999999999,
 7.499999999999999,
 7.799999999999999,
 8.099999999999998,
 8.399999999999999,
 8.7,
 8.999999999999998]

In [147]:
np.arange(1,9) #arange includes the upperbound in float dtype but integer dtype it excludes upper bound

array([1, 2, 3, 4, 5, 6, 7, 8])

In [158]:
np.linspace(1,10,5) #generates the data inbetween line

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [159]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [164]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [165]:
np.ones(4)

array([1., 1., 1., 1.])

In [166]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [167]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [168]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [170]:
np.empty((3,4))

array([[1.04157884e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [4.00766127e+175, 6.23659072e+174, 6.86568156e+169,
        5.53710188e+174],
       [2.34444201e-056, 6.59472307e-066, 1.10635102e-046,
        2.14703913e+184]])

In [180]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [185]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [188]:
np.linspace([1,6],4, endpoint=False, axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [194]:
np.logspace([2,3], 4, axis=0)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [197]:
d = np.linspace(4,7,40)
d


array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [198]:
d.ndim

1

In [199]:
d.shape

(40,)

In [200]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [202]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [206]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])