In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,5,"ram", 4+8j])

array(['1', '2', '3', '4', '5', 'ram', '(4+8j)'], dtype='<U64')

In [7]:
np.array([1,23,1,2,5.0])

array([ 1., 23.,  1.,  2.,  5.])

it upcasts all the data into biggest nature of data type

In [9]:
np.array([[1,3],[2,5],[6,7]])

array([[1, 3],
       [2, 5],
       [6, 7]])

In [10]:
np.array([[1,3],[2,5],[6,7,8]])

C:\Users\SAIRAM~1\AppData\Local\Temp/ipykernel_37912/1446999149.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[2,5],[6,7,8]])


array([list([1, 3]), list([2, 5]), list([6, 7, 8])], dtype=object)

In [14]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [18]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [19]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
arr = np.array([(1,2),(3,4)],dtype = [("a",'<i4'),("b",'<i8')])

In [40]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [41]:
type(arr[0][0])

numpy.int32

In [42]:
type(arr[0][1])

numpy.int64

In [43]:
arr[1][1]

4

In [44]:
type(arr[1][1])

numpy.int64

In [45]:
arr = np.array([[1,3],[3,4]])

In [46]:
arr

array([[1, 3],
       [3, 4]])

## array vs matrix

In [54]:
mat = np.mat(arr)
mat

matrix([[1, 3],
        [3, 4]])

In [48]:
l = [3,4,5,6,7]

In [49]:
np.array(l)

array([3, 4, 5, 6, 7])

In [50]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [56]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [57]:
np.asanyarray(mat) #which wont convert any kind of array

matrix([[1, 3],
        [3, 4]])

In [59]:
np.asarray(mat) #which converts the data type to array

array([[1, 3],
       [3, 4]])

In [60]:
issubclass(np.matrix, np.ndarray)

True

In [61]:
issubclass(np.ndarray, np.matrix)

False

In [65]:
a = arr
a

array([[1, 3],
       [3, 4]])

In [66]:
b = np.copy(arr)  #
b

array([[1, 3],
       [3, 4]])

In [72]:
arr[0][0] = 67 #array elements are mutable

In [73]:
arr #shallow copy - 

array([[67,  3],
       [ 3,  4]])

In [74]:
a

array([[67,  3],
       [ 3,  4]])

In [75]:
b

array([[1, 3],
       [3, 4]])

In [76]:
b[0][0] = 68  #deep copy --

In [77]:
b

array([[68,  3],
       [ 3,  4]])

In [78]:
arr[0:]

array([[67,  3],
       [ 3,  4]])

In [79]:
arr[-1]

array([3, 4])

In [80]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [83]:
np.fromfunction(lambda i, j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [85]:
type(np.fromfunction(lambda i, j :i==j,(4,4)))

numpy.ndarray

In [86]:
np.fromfunction(lambda i, j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [87]:
np.fromfunction(lambda i, j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [88]:
np.fromfunction(lambda i, j :i/j,(3,3))

C:\Users\SAIRAM~1\AppData\Local\Temp/ipykernel_37912/2665923418.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j :i/j,(3,3))
C:\Users\SAIRAM~1\AppData\Local\Temp/ipykernel_37912/2665923418.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [92]:
[i*i for i in range(5)] #list comprehension

[0, 1, 4, 9, 16]

In [91]:
def test(x):
    yield x

In [93]:
test(5)

<generator object test at 0x000001EADB77A200>

In [94]:
gen = (i*i for i in range(5))

In [95]:
gen

<generator object <genexpr> at 0x000001EADB77A510>

In [97]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [98]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [102]:
gen
for i in gen:
    print(i)

In [105]:
np.fromstring("1,2,3,6,5",sep = ',', dtype = int)

array([1, 2, 3, 6, 5])

In [109]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [4,5,6,7]])

In [110]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [111]:
type(arr1)

numpy.ndarray

In [112]:
arr1.ndim

2

In [113]:
arr1.size

12

In [114]:
arr1.shape

(3, 4)

In [115]:
arr1.dtype

dtype('int32')

In [116]:
arr.size

4

In [117]:
arr.ndim

2

In [118]:
arr.shape

(2, 2)

In [124]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [125]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [128]:
arr2.size

16

In [129]:
arr2.ndim

3

In [130]:
arr2.shape

(2, 2, 4)

In [133]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [134]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [135]:
arr4.ndim

4

In [136]:
arr4.shape

(1, 4, 2, 4)